# Generated by Django 5.0.12 on 2025-05-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_order_orderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="qantity",
            new_name="quantity",
        ),
    ]
